/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Budget */
        get: operations["get_budget_budget_get"];
        /** Update Budget */
        put: operations["update_budget_budget_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Campaigns */
        get: operations["list_campaigns_campaigns_get"];
        put?: never;
        /**
         * Create Campaign
         * @description Creates the campaign and queues company discovery for each segment (worker).
         */
        post: operations["create_campaign_campaigns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Campaign */
        get: operations["get_campaign_campaigns__campaign_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Csv */
        post: operations["import_csv_campaigns__campaign_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaign_id}/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Prospects */
        get: operations["list_prospects_campaigns__campaign_id__prospects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offer-profiles/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Runs Agent 1 (offer analyst). Can take up to a few minutes with a real LLM.
         */
        post: operations["analyze_offer_profiles_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offer-profiles/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Profile */
        get: operations["current_profile_offer_profiles_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offer-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update */
        put: operations["update_offer_profiles__profile_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offer-profiles/{profile_id}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Segments */
        get: operations["list_segments_offer_profiles__profile_id__segments_get"];
        put?: never;
        /**
         * Generate Segments
         * @description Runs Agent 2 (ICP strategist) on a validated profile; replaces previous segments.
         */
        post: operations["generate_segments_offer_profiles__profile_id__segments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offer-profiles/{profile_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_offer_profiles__profile_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospects/{prospect_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prospect */
        get: operations["get_prospect_prospects__prospect_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/segments/{segment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Select Segment */
        patch: operations["select_segment_segments__segment_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeOfferRequest */
        AnalyzeOfferRequest: {
            /** Description */
            description?: string | null;
            /** Website Url */
            website_url?: string | null;
        };
        /** BudgetStatus */
        BudgetStatus: {
            /** Limit Eur */
            limit_eur: number;
            /** Ratio */
            ratio: number;
            /**
             * Resets At
             * Format: date-time
             */
            resets_at: string;
            /** Spent Eur */
            spent_eur: number;
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "warning" | "exhausted";
        };
        /** BudgetUpdate */
        BudgetUpdate: {
            /** Daily Limit Eur */
            daily_limit_eur: number;
        };
        /** CampaignCreate */
        CampaignCreate: {
            /** Companies Per Segment */
            companies_per_segment?: number | null;
            /** Name */
            name: string;
            /** Segment Ids */
            segment_ids: string[];
        };
        /** CampaignRead */
        CampaignRead: {
            /** Companies Per Segment */
            companies_per_segment: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            jobs: components["schemas"]["JobProgress"];
            /** Name */
            name: string;
            /** Segment Ids */
            segment_ids: string[];
        };
        /** CompanySummary */
        CompanySummary: {
            /** City */
            city: string | null;
            /** Departement */
            departement: string | null;
            /** Domain Evidence Url */
            domain_evidence_url: string | null;
            /** Domain Status */
            domain_status: string;
            /** Headcount Range */
            headcount_range: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Sole Trader */
            is_sole_trader: boolean;
            /** Naf Code */
            naf_code: string | null;
            /** Name */
            name: string;
            /** Siren */
            siren: string | null;
            /** Source Provider */
            source_provider: string;
            /** Website Domain */
            website_domain: string | null;
        };
        /** ContactSummary */
        ContactSummary: {
            /** Email */
            email: string | null;
            /** First Name */
            first_name: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Generic */
            is_generic: boolean;
            /** Last Name */
            last_name: string | null;
            /** Source Provider */
            source_provider: string;
            /** Title */
            title: string | null;
            /** Verification Status */
            verification_status: string;
        };
        /** CsvImportRequest */
        CsvImportRequest: {
            /** Csv */
            csv: string;
        };
        /** CsvImportResult */
        CsvImportResult: {
            /** Already In Campaign */
            already_in_campaign: number;
            /** Errors */
            errors: string[];
            /** Imported */
            imported: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            mode: components["schemas"]["RunMode"];
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /** JobProgress */
        JobProgress: {
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * OfferProfileData
         * @description Output of Agent 1. Lists may be empty: never fill gaps with guesses.
         */
        OfferProfileData: {
            /** Company Name */
            company_name: string | null;
            /** Competitors Mentioned */
            competitors_mentioned: components["schemas"]["SourcedClaim"][];
            /** Differentiators */
            differentiators: components["schemas"]["SourcedClaim"][];
            /**
             * Geography
             * @description Where they operate.
             */
            geography: components["schemas"]["SourcedClaim"][];
            /**
             * Missing Information
             * @description Important facts that the sources do not contain.
             */
            missing_information: string[];
            /**
             * Offerings
             * @description Products or services.
             */
            offerings: components["schemas"]["SourcedClaim"][];
            /**
             * Pricing
             * @description Only if prices are public.
             */
            pricing: components["schemas"]["SourcedClaim"][];
            /**
             * Proof Points
             * @description Named customers, figures, certifications, awards.
             */
            proof_points: components["schemas"]["SourcedClaim"][];
            /**
             * Summary
             * @description Two or three sentences: what the company sells and to whom.
             */
            summary: string;
            /** Target Customers */
            target_customers: components["schemas"]["SourcedClaim"][];
            value_proposition: components["schemas"]["SourcedClaim"] | null;
        };
        /** OfferProfileRead */
        OfferProfileRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            data: components["schemas"]["OfferProfileData"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Pages Fetched */
            pages_fetched: string[];
            /** Source Description */
            source_description: string | null;
            /** Source Url */
            source_url: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "validated";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Validated At */
            validated_at: string | null;
            /** Warnings */
            warnings: string[];
        };
        /** OfferProfileUpdate */
        OfferProfileUpdate: {
            data: components["schemas"]["OfferProfileData"];
        };
        /** ProspectDetail */
        ProspectDetail: {
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            company: components["schemas"]["CompanySummary"];
            contact: components["schemas"]["ContactSummary"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Segment Id */
            segment_id: string | null;
            /** State */
            state: string;
            /** State Reason */
            state_reason: string | null;
            /** Transitions */
            transitions: components["schemas"]["TransitionRead"][];
        };
        /** ProspectRow */
        ProspectRow: {
            company: components["schemas"]["CompanySummary"];
            contact: components["schemas"]["ContactSummary"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Segment Id */
            segment_id: string | null;
            /** State */
            state: string;
            /** State Reason */
            state_reason: string | null;
        };
        /**
         * RunMode
         * @description What the application is allowed to do with emails.
         *
         *     - DEMO: fake LLM, fake data providers, emails captured by Mailpit. No API key needed.
         *     - DRY_RUN: real LLM and data providers, but every email is captured by Mailpit.
         *     - LIVE: emails really leave. Requires DRY_RUN=false *and* a confirmation in the UI.
         * @enum {string}
         */
        RunMode: "DEMO" | "DRY_RUN" | "LIVE";
        /** SegmentCriteria */
        SegmentCriteria: {
            /**
             * Departements
             * @description French département codes ('75', '2A'); empty = all France.
             */
            departements: string[];
            /**
             * Headcount Ranges
             * @description INSEE 'tranche d'effectif salarié' codes.
             */
            headcount_ranges: ("NN" | "00" | "01" | "02" | "03" | "11" | "12" | "21" | "22" | "31" | "32" | "41" | "42" | "51" | "52" | "53")[];
            /**
             * Keywords
             * @description Short search keywords.
             */
            keywords: string[];
            /**
             * Naf Codes
             * @description NAF rév. 2 sub-class codes, format '62.01Z'.
             */
            naf_codes: string[];
        };
        /** SegmentRead */
        SegmentRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            criteria: components["schemas"]["SegmentCriteria"];
            /** Description */
            description: string;
            /** Fit Rationale */
            fit_rationale: string;
            /** Fit Score */
            fit_score: number;
            /** Hook Angle */
            hook_angle: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Main Pain */
            main_pain: string;
            /** Name */
            name: string;
            /**
             * Offer Profile Id
             * Format: uuid
             */
            offer_profile_id: string;
            /** Position */
            position: number;
            /** Selected */
            selected: boolean;
            /** Target Titles */
            target_titles: string[];
        };
        /** SegmentSelection */
        SegmentSelection: {
            /** Selected */
            selected: boolean;
        };
        /** SourcedClaim */
        SourcedClaim: {
            /**
             * Claim
             * @description One factual statement.
             */
            claim: string;
            /**
             * Excerpt
             * @description Exact sentence or phrase copied from that source, supporting the claim.
             */
            excerpt: string;
            /**
             * Source Url
             * @description URL of a page you fetched that supports the claim, or 'user-input:description' if it comes from the user's description.
             */
            source_url: string;
        };
        /** TransitionRead */
        TransitionRead: {
            /** Actor */
            actor: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** From State */
            from_state: string | null;
            /** Reason */
            reason: string | null;
            /** To State */
            to_state: string;
        };
        /** UserRead */
        UserRead: {
            /** Email */
            email: string;
            /** Is Demo */
            is_demo: boolean;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    get_budget_budget_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetStatus"];
                };
            };
        };
    };
    update_budget_budget_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BudgetUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_campaigns_campaigns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"][];
                };
            };
        };
    };
    create_campaign_campaigns_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CampaignCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_campaign_campaigns__campaign_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_csv_campaigns__campaign_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CsvImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsvImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_prospects_campaigns__campaign_id__prospects_get: {
        parameters: {
            query?: {
                state?: string | null;
                segment_id?: string | null;
            };
            header?: never;
            path: {
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    analyze_offer_profiles_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeOfferRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_profile_offer_profiles_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferProfileRead"];
                };
            };
        };
    };
    update_offer_profiles__profile_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferProfileUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_segments_offer_profiles__profile_id__segments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_segments_offer_profiles__profile_id__segments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_offer_profiles__profile_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferProfileRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prospect_prospects__prospect_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prospect_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProspectDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_segment_segments__segment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                segment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SegmentSelection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SegmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
