"""phase 2 discovery

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 17:53:33.287180
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("siren", sa.String(length=9), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("naf_code", sa.String(length=6), nullable=True),
        sa.Column("headcount_range", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=5), nullable=True),
        sa.Column("city", sa.String(length=200), nullable=True),
        sa.Column("departement", sa.String(length=3), nullable=True),
        sa.Column("is_sole_trader", sa.Boolean(), nullable=False),
        sa.Column("website_domain", sa.String(length=253), nullable=True),
        sa.Column("domain_source", sa.String(length=20), nullable=True),
        sa.Column("domain_status", sa.String(length=20), nullable=False),
        sa.Column("domain_evidence_url", sa.String(length=2048), nullable=True),
        sa.Column("officers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_provider", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "domain_status IN ('unknown', 'confirmed', 'unconfirmed', 'not_found')",
            name=op.f("ck_companies_domain_status"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_companies_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )
    op.create_index(op.f("ix_companies_workspace_id"), "companies", ["workspace_id"], unique=False)
    op.create_index(
        "uq_companies_workspace_domain",
        "companies",
        ["workspace_id", "website_domain"],
        unique=True,
        postgresql_where=sa.text("website_domain IS NOT NULL"),
    )
    op.create_index(
        "uq_companies_workspace_siren",
        "companies",
        ["workspace_id", "siren"],
        unique=True,
        postgresql_where=sa.text("siren IS NOT NULL"),
    )
    op.create_table(
        "jobs",
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'dead')", name=op.f("ck_jobs_status")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_jobs_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_jobs_idempotency_key")),
    )
    op.create_index(op.f("ix_jobs_correlation_id"), "jobs", ["correlation_id"], unique=False)
    op.create_index("ix_jobs_pick", "jobs", ["status", "run_after"], unique=False)
    op.create_index(op.f("ix_jobs_workspace_id"), "jobs", ["workspace_id"], unique=False)
    op.create_table(
        "provider_calls",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("credits_used", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_provider_calls_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_calls")),
    )
    op.create_index(
        "ix_provider_calls_lookup",
        "provider_calls",
        ["provider", "operation", "request_hash"],
        unique=False,
    )
    op.create_index(
        "ix_provider_calls_workspace_created",
        "provider_calls",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_calls_workspace_id"), "provider_calls", ["workspace_id"], unique=False
    )
    op.create_table(
        "campaigns",
        sa.Column("offer_profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("target_country", sa.String(length=2), nullable=False),
        sa.Column("companies_per_segment", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("target_country = 'FR'", name=op.f("ck_campaigns_france_only")),
        sa.ForeignKeyConstraint(
            ["offer_profile_id"],
            ["offer_profiles.id"],
            name=op.f("fk_campaigns_offer_profile_id_offer_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaigns_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(
        op.f("ix_campaigns_offer_profile_id"), "campaigns", ["offer_profile_id"], unique=False
    )
    op.create_index(op.f("ix_campaigns_workspace_id"), "campaigns", ["workspace_id"], unique=False)
    op.create_table(
        "contacts",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("is_generic", sa.Boolean(), nullable=False),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_provider", sa.String(length=20), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('unverified', 'valid', 'accept_all', 'unknown', 'invalid', 'webmail', 'disposable')",
            name=op.f("ck_contacts_verification_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_contacts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contacts")),
    )
    op.create_index(op.f("ix_contacts_company_id"), "contacts", ["company_id"], unique=False)
    op.create_index(op.f("ix_contacts_workspace_id"), "contacts", ["workspace_id"], unique=False)
    op.create_index(
        "uq_contacts_workspace_email_hash",
        "contacts",
        ["workspace_id", "email_hash"],
        unique=True,
        postgresql_where=sa.text("email_hash IS NOT NULL"),
    )
    op.create_table(
        "campaign_segments",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("segment_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_segments_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
            name=op.f("fk_campaign_segments_segment_id_segments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaign_segments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("campaign_id", "segment_id", name=op.f("pk_campaign_segments")),
    )
    op.create_index(
        op.f("ix_campaign_segments_workspace_id"),
        "campaign_segments",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "prospects",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("segment_id", sa.Uuid(), nullable=True),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("state_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "state IN ('discovered', 'contact_found', 'email_verified', 'researched', 'drafted', 'qa_passed', 'awaiting_approval', 'scheduled', 'sent', 'replied', 'bounced', 'unsubscribed', 'completed', 'failed', 'excluded')",
            name=op.f("ck_prospects_state"),
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_prospects_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_prospects_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contacts.id"],
            name=op.f("fk_prospects_contact_id_contacts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["segments.id"],
            name=op.f("fk_prospects_segment_id_segments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_prospects_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospects")),
        sa.UniqueConstraint("campaign_id", "company_id", name="uq_prospects_campaign_company"),
    )
    op.create_index(op.f("ix_prospects_campaign_id"), "prospects", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_prospects_company_id"), "prospects", ["company_id"], unique=False)
    op.create_index(op.f("ix_prospects_segment_id"), "prospects", ["segment_id"], unique=False)
    op.create_index(op.f("ix_prospects_workspace_id"), "prospects", ["workspace_id"], unique=False)
    op.create_table(
        "prospect_transitions",
        sa.Column("prospect_id", sa.Uuid(), nullable=False),
        sa.Column("from_state", sa.String(length=30), nullable=True),
        sa.Column("to_state", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("actor", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prospect_id"],
            ["prospects.id"],
            name=op.f("fk_prospect_transitions_prospect_id_prospects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_prospect_transitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prospect_transitions")),
    )
    op.create_index(
        op.f("ix_prospect_transitions_prospect_id"),
        "prospect_transitions",
        ["prospect_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prospect_transitions_workspace_id"),
        "prospect_transitions",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prospect_transitions_workspace_id"), table_name="prospect_transitions")
    op.drop_index(op.f("ix_prospect_transitions_prospect_id"), table_name="prospect_transitions")
    op.drop_table("prospect_transitions")
    op.drop_index(op.f("ix_prospects_workspace_id"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_segment_id"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_company_id"), table_name="prospects")
    op.drop_index(op.f("ix_prospects_campaign_id"), table_name="prospects")
    op.drop_table("prospects")
    op.drop_index(op.f("ix_campaign_segments_workspace_id"), table_name="campaign_segments")
    op.drop_table("campaign_segments")
    op.drop_index(
        "uq_contacts_workspace_email_hash",
        table_name="contacts",
        postgresql_where=sa.text("email_hash IS NOT NULL"),
    )
    op.drop_index(op.f("ix_contacts_workspace_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_company_id"), table_name="contacts")
    op.drop_table("contacts")
    op.drop_index(op.f("ix_campaigns_workspace_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_offer_profile_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_provider_calls_workspace_id"), table_name="provider_calls")
    op.drop_index("ix_provider_calls_workspace_created", table_name="provider_calls")
    op.drop_index("ix_provider_calls_lookup", table_name="provider_calls")
    op.drop_table("provider_calls")
    op.drop_index(op.f("ix_jobs_workspace_id"), table_name="jobs")
    op.drop_index("ix_jobs_pick", table_name="jobs")
    op.drop_index(op.f("ix_jobs_correlation_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        "uq_companies_workspace_siren",
        table_name="companies",
        postgresql_where=sa.text("siren IS NOT NULL"),
    )
    op.drop_index(
        "uq_companies_workspace_domain",
        table_name="companies",
        postgresql_where=sa.text("website_domain IS NOT NULL"),
    )
    op.drop_index(op.f("ix_companies_workspace_id"), table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
